[project]
name = "data-mining"
version = "0.4.3"
description = "Data Mining Homeworks"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "nbstripout>=0.8.1",
    "pandas>=2.3.3",
    "pyspark>=4.0.1",
]
